name: zodgame_autoreply

on:
#   schedule:
#   - cron: "0 0 * * *"
  
#   push:
#     branches: [ checkinAndreply ]
#   pull_request:
#     branches: [ checkinAndreply ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip3 install -r ./zodgame/requirements.txt
    - name: Run 
      run: |
        python3 ./zodgame/zodgame.py "${{secrets.ZODGAME_COOKIE}}"
    - uses: gautamkrishnar/keepalive-workflow@master
